name: "Deploy K8S with AWS"

on:
  push:
    paths:
    - 'terraform-aws-eks-ci-cd/**' 
    - '.github/workflows/deploy.yml'
    branches:
    - master
  workflow_dispatch:

jobs:
  terraform-CI:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
         terraform_version: latest
         terraform_wrapper: false
     
     - name: Terraform Format
       id: fmt
       run: terraform fmt
       
     - name: Terraform Init
       id: init
       run: terraform init

     - name: Terraform Plan
       id: plan
       run: terraform plan -no-color

     - name: Terraform Apply
       run: terraform apply -auto-approve

     - name: Terraform Destroy
       run: terraform destroy -auto-approve